### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by DCRichards** [drone-plugins/drone-volume-cache#3] opened 2017-06-28 13:04 UTC
Nobody currently knows how to use this...

**Comment by krisleech** [comment] 2017-08-15 10:32
My first attempt:

```
pipeline:
  restore-cache:
    image: plugins/volume-cache
    restore: true
    mount:
      - ./bundle_cache
    volumes:
      - /tmp/cache:/cache
```

but I get an error `Cache could not be restored open /cache/Propheris/oxygen/.tar: no such file or directory`.

**Comment by bugbuilder** [comment] 2017-08-21 04:06
@krisleech at this moment the filepath has a bad reference to the repo branch name, to avoid this you need to add the file option to the pluging

```
pipeline:
  restore-cache:
    image: plugins/volume-cache
    file: cache.tar
    restore: true
    mount:
      - ./bundle_cache
    volumes:
      - /tmp/cache:/cache
      
  test:
    image: do/something
    commands:
      - mkdir -p ./bundle_cache
      - touch ./bundle_cache/test
      - touch ./bundle_cache/test2

      
  rebuild-cache:
    image: plugins/volume-cache
    file: cache.tar
    rebuild: true
    mount:
      - ./bundle_cache
    volumes:
      - /tmp/cache:/cache      
```

**Comment by tboerger** [comment] 2017-08-21 06:26
I would call it more or less a duplicate of https://github.com/drone-plugins/drone-volume-cache/issues/1 as this would also include a local readme.

**Closed as completed by tboerger** 2017-08-21 06:26 UTC

**Comment by krisleech** [comment] 2017-08-22 10:09
@bugbuilder Thanks, but I get an error adding `file` as such:

```
time="2017-08-22T10:06:19Z" level=info msg="Restoring cache from /cache/cache.tar" 
time="2017-08-22T10:06:19Z" level=warning msg="Failed to retrieve /cache/cache.tar, trying /cache/Propheris/carbon/.tar" 
time="2017-08-22T10:06:19Z" level=warning msg="Cache could not be restored open /cache/Propheris/carbon/.tar: no such file or directory" 
time="2017-08-22T10:06:19Z" level=info msg="Cache restored" 
```

This happens on subsequent builds too.

**Comment by krisleech** [comment] 2017-08-22 10:13
Oh I see, this is just a warning, because there is no cache until the next build. Thanks. I see there is a PR for a README too, this is great.

**Comment by krisleech** [comment] 2017-08-22 10:36
I see the cache is only built if the build passes. That explains it. Thanks again.
